# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: main workflow

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  get-resources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: "Run application"
      run: python app.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: builded
        path: ./_deploy
  docker-build:
    needs: get-resources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: builded
        path: ./_deploy
    - name: Docker build and push
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        VERSION=$GITHUB_SHA
        docker build . --file Dockerfile --tag rasooll/mrtehran-music-json:$VERSION
        docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
        docker tag rasooll/mrtehran-music-json:$VERSION rasooll/mrtehran-music-json:latest
        docker push rasooll/mrtehran-music-json:$VERSION
        docker push rasooll/mrtehran-music-json:latest
  kubernetes-deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/mrtehran mrtehran=rasooll/mrtehran-music-json:$GITHUB_SHA
    - name: verify deployment
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: '"rollout status deployment/mrtehran"'